### ISSUE TITLE
sb

### ISSUE THREAD

**Issue by 419632131** [CaiWanFeng/CustomPictureInPicture#3]
sb qiongbi demo is ¥200

**Comment by CaiWanFeng** [comment]
你又不是我儿子，为什么要免费给你？智商有点捉急啊

**Comment by CaiWanFeng** [comment]
> sb qiongbi demo is ¥200

你又不是我儿子，为什么要免费给你？就因为你是废物且脑残？

**Comment by CaiWanFeng** [comment]
> sb qiongbi demo is ¥200

不要在其它地方跟我瞎BB了，我最后回复你一次：
1. 你是唯一一个要不到代码就骂人的，你这种行为就是脑残中的战斗机，你这么喜欢要，建议去要饭；
2. 你说我骂人素质低。对于你这种先骂人的脑残，辱骂是最适合你的方式；
3. 你张口闭口都在说别人穷逼，请问你是哪家的公子哥连200块都给不起？张口闭口都是穷逼，你对穷就这么敏感吗？难道你才是你口中的穷逼？
4. 总结一下：你就是一个能力不行、智力低下、适合要饭的自卑狗。😄
